version: '2'
services:
  rabbitmq:
    image: rabbitmq:management
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/mnesia
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
#    environment:
#      RABBITMQ_ERLANG_COOKIE: "mysecretcookie"
    ports:
      - 5672:5672
      - 15672:15672
